# Generated by Django 5.2.5 on 2025-08-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField()),
                ('category', models.CharField()),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('color', models.CharField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
